food/urls.py
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('', views.IndexClassView.as_view(), name ='index'),
    path('item/',views.item, name = 'item'),
    path('<int:pk>/',views.FoodDetail.as_view(),name = 'detail'),
    path('add',views.CreateItem.as_view(),name = 'create_item'),
    path('update/<int:id>',views.update_item,name = 'update_item'),
    path('delete/<int:id>',views.delete_item,name = 'delete_item'),
]

mysite/urls.py
from django.contrib import admin    
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from calories import views as calories_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('food.urls')),
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
    path('calories/',calories_views.index,name='calories'),
    path('delete/<int:id>/',calories_views.delete_consume,name='delete'),
   
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calories/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Food(models.Model):

    def __str__(self):
        return self.name
    
    name = models.CharField(max_length= 100)
    carbs = models.FloatField()
    protein = models.FloatField()
    fats = models.FloatField()
    calories = models.IntegerField()

class Consume(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food_consumed = models.ForeignKey(Food,on_delete=models.CASCADE)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default = "https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    


    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

        

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model= User
        fields = ['username','email','password1','password2']

calories/views.py
from django.shortcuts import redirect, render
from .models import Consume, Food
# Create your views here.
def index(request):
    if request.method == "POST":
        food_consumed = request.POST['food_consumed']
        consume = Food.objects.get(name = food_consumed)
        user = request.user
        consume = Consume(user=user,food_consumed = consume)
        consume.save()
        foods = Food.objects.all()

    else:
        
        foods = Food.objects.all()
    consumed_food = Consume.objects.filter(user = request.user)
    return render(request,'calories/index.html',{'foods':foods,'consumed_food':consumed_food})

def delete_consume(request,id):
    consumed_food = Consume.objects.get(id = id)
    if request.method == 'POST':
        consumed_food.delete()
        return redirect('/calories')
    return render(request,'calories/delete.html')

food/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from food.forms import ItemForm
from .models import Item
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.core.paginator import Paginator
# Create your views here.

def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list' : item_list,
    }
    paginator = Paginator(item_list,2)
    page = request.GET.get('page')
    food_objects = paginator.get_page(page)
    return render(request,'food/index.html',context)

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name ='item_list'
    paginate_by = 3



class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def item(request):
    return HttpResponse('<h1>This is an item view<h1>')

def detail(request,item_id):
    item = Item.objects.get(pk = item_id)
    context = {
        'item' : item
    }
    return render(request,'food/detail.html',context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html' 

def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form})

def update_item(request,id):
    item =Item.objects.get(id = id)
    form = ItemForm(request.POST or None, instance = item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render (request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

calories/templates/calories/delete.html
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        Are you sure you want to delete {{item.item_name}} ?
        <button type="submit">Confirm</button>
        <a href="{%url 'calories' %}" class="btn" type="submit">Cancel</a>
    </form>    
</body>
</html>

calories/templates/calories/index.html
{% extends 'food/base.html' %}

{% block body %}
<style>
input {
    border: none;
    background: transparent;
}
</style>
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    </head>
    <body>
    <div>
            <br><br><br>
            <h4>Calories Goal 2000KCal</h4>
            <br>
            <div class = "row">
                <div class = "col-md-9 offset-1">
                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="0"></div>
                   
                    <input type="text" id="mytext"> 
                </div>
                </div>
            </div>
            <br>
            <br>
            <br>
      
        <div class = "container">
            <div class = "row">
                <div class = "col-md-12">
                    <form method ="POST" action="">
                        <div class="form-group row">
                        {%csrf_token%}
                        <label class = "col-md-2">
                            <b>Select Food To Add</b>
                        </label>
                        <select class = "col-md-6 form-control" name="food_consumed" id="food_consumed">
                            {%for food in foods%}
                            <option value="{{food.name}}">{{food.name}}</option>
                            {%endfor%}
                        </select>
                        <button class = "btn btn-success" type="submit">Add</button>
                        </div>
                    </form>                    
                </div>
            </div>
        </div>
            

        <div class = "row">
            <div class ="col-md-6">
                <div>
                    <h4> Today's Consumption </h4>
                </div>

                <table id = "table" class = "table table-striped table-primary">
                    <tr class="bg-primary text-white">
                        <th>Food item</th>
                        <th>Carb(gm)</th>
                        <th>Protein(gm)</th>
                        <th>Fats(gm)</th>
                        <th>Calories(Kcal)</th>
                        <th>Remove Item</th>
                    </tr>
                        {%for c in consumed_food%}
                    <tr>
                        <td>{{c.food_consumed.name}}</td>
                        <td>{{c.food_consumed.carbs}}</td>
                        <td>{{c.food_consumed.protein}}</td>
                        <td>{{c.food_consumed.fats}}</td>
                        <td>{{c.food_consumed.calories}}</td>
                        <td><a class = "btn btn-danger" href="{% url 'delete' c.id%}">X</a></td>
                    </tr>
                        {%endfor%}

                    <tr>
                        <td id = "name"><b>Total</b></td>
                        <td id = "totalCarbs"><b>Total</b></td>
                        <td id = "totalProtein"><b>Total</b></td>
                        <td id = "totalFats"><b>Total</b></td>
                        <td id = "totalCalories"><b>Total</b></td>
                    </tr>


                </table>
                
            </div>
            <div class = "col-md-5">
                <div class="">
                    <h4>Today's breakdown</h4>
                </div>
                <div class = "text-white bg-primary">
                    <h3>Macronutirents breakdown</h3>
                </div>
                <div class="col-mid-12">
                    <canvas id="myChart" width="400" height="400"></canvas>
 
                </div>
        </div>

    </body>

<script>
    var table = document.getElementById("table");
    var carbs = 0,protein = 0, fats = 0, calories = 0;
    for(var i=1; i<table.rows.length-1;i++){
        console.log(table.rows[i].cells[1].innerHTML);
        carbs += parseFloat(table.rows[i].cells[1].innerHTML);
        carbs = Math.round(carbs);
        protein += parseFloat(table.rows[i].cells[2].innerHTML);
        protein = Math.round(protein)
        fats += parseFloat(table.rows[i].cells[3].innerHTML);
        fats = Math.round(fats);
        calories += parseFloat(table.rows[i].cells[4].innerHTML);
        calories = Math.round(calories);
    }
    console.log(carbs);

    document.getElementById("totalCarbs").innerHTML ='<b>' + carbs +'(gm)</b>';
    document.getElementById("totalProtein").innerHTML ='<b>'+ protein  +'(gm)</b>';
    document.getElementById("totalFats").innerHTML = '<b>' + fats  +'(gm)</b>';
    document.getElementById("totalCalories").innerHTML = '<b>' + calories  +'(Kcal)</b>';

    var calPer = (calories/2000)*100;
    document.getElementsByClassName("progress-bar")[0].setAttribute("style","width:" +calPer+"%");
    document.getElementById("mytext").value = Math.round(calPer) + "% Completed";

    var total = carbs + protein + fats;
    var carbsP = Math.round((carbs/total)*100);
    var proteinP = Math.round((protein/total)*100);
    var fatsP = Math.round((fats/total)*100);

    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
    type: 'doughnut',
    data: {
        labels: ['Carbs' + carbsP + '%', 'Protein'+ proteinP + '%', 'Fats'+ fatsP + '%'],
        datasets: [{
        label: '# of Votes',
        data: [carbsP,proteinP,fatsP],
        backgroundColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                
            ],
        borderWidth: 1
        }]
    },
    options: {
        maintainAspectRatio: false,
    }
   
    });
</script>
</html>
{% endblock %}

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href=" {%static 'food/style.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class = "navbar navbar-dark bg-dark" >
        <a href="{%url 'food:index' %}" class="navbar-brand">FoodApp</a>
        <div class = "navbar">
            {%if user.is_authenticated %}
                <a class="nav-item nav-link" href ="{% url 'food:create_item'%}">Add Item</a>
                <a class="nav-item nav-link" href ="{% url 'calories'%}">Calories Tracker</a>
                <a class="nav-item nav-link" href="{% url 'profile'%}">User Profile</a>  
                <a class="nav-item nav-link" href="{% url 'logout'%}">Logout</a>  
            {%else%}
            <a class="nav-item nav-link" href ="{% url 'calories'%}">Calories Tracker</a>
                <a class="nav-item nav-link" href="{% url 'login'%}">Login</a>
            {% endif %}
        </div>
    </nav>
    
    {% block body %}
    {% endblock %}

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{message}}
        </div>
        {%endfor%}
    {%endif%}

</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{%block body%}
<div class="container">
    <div class = "row">
        <div class = "col-md-6">
            <img height =300px src="{{item.item_image}}" class="card"/>
        </div>

        <div class = "col-md-6">
            <h1>{{object.item_name}}</h1>
            <h2>{{object.item_desc}}</h2>
            <h3>${{object.item_price}}</h3>
            {%if user.is_authenticated %}
            <h6>Uploaded by user: {{item.user_name}}</h6>
            <a href="{% url 'food:delete_item' item.id%}" class="btn btn-info" role="button">Delete</a>
            {% endif %}
            <a href="{%url 'food:index' %}" class="btn btn-success">Return To Main Menu</a>
        </div>
    </div>
</div>

{% endblock %}   

food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href=" {%static 'food/style.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>

    {%block body%}
    {% for item in item_list %}
    <div class = "row">
        <div class ="col-md-3 offset-md-2">
            <img class = "card" height = "150px" src="{{item.item_image}}"/>
        </div>
        <div class ="col-md-3">
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_desc}}</h5>
            <h6>{{item.item_price}}</h6>
   
        </div>
        <div class ="col-md-1">
            <a href="{%url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
        {%if user.is_authenticated %}
        <div class ="col-md-1">
            <a href="{%url 'food:update_item' item.id %}" class="btn btn-success">Edit</a>
        </div>

        <div class ="col-md-1">
            <a href="{%url 'food:delete_item' item.id %}" class="btn btn-success">Delete</a>
        </div>
        {%endif%}
    </div>
    {% endfor %}  
    
    <div class ="col-md-3 offset-md-8">
        <div class="btn-group" role="group" aria-label="Item pagination">
    {% if is_paginated %}
        <ul class="pagination">
        {% if page_obj.has_previous %}
        <li>
            <a href="?page=1">First </a>
            <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
        </li>
        {% endif %}

         <li class="">
        <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}. </span>
        </li>

        {% if page_obj.has_next %}
            <li>
            <span><a href="?page={{ page_obj.next_page_number }}">Next </a></span>
            <a href="?page={{ page_obj.paginator.num_pages}}">Last</a>
        </li>
        {% endif %}
    </ul>

    {% endif %}
    </div>
    </div>

    {% endblock %}    


</body>
</html>

food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}} ?</h2>

    <button type="submit">Confirm</button>
    <a href="{%url 'food:index' %}" class="btn" type="submit">Cancel</a>
</form>

food/templates/food/item-form.html
{%extends 'food/base.html'%}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                    
                        {{form}}
                                       
                        <button type="submit">Save</button>
                        <a href="{%url 'food:index' %}" class="btn" type="submit">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {%for field in form%}
                            <div class ="form-group">
                                {{field.name}}
                                {{field}}
                            </div>
                        {%endfor%}

                        <button class="btn-info" type="submit">Login</button>
                        <a href="{%url 'register' %}">
                            Register
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

users/templates/users/logout.html
<h1>You have been logged out</h1>
<a href="{%url 'food:index' %}" class="btn btn-success">Return To Main Menu</a>

users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img width="100px" height="100px" src="{{user.profile.image.url}}">

users/templates/users/register.html
{%extends 'food/base.html'%}

{% block body%}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {%for field in form%}
                            <div class = "form-group">
                                {{field.name}}
                                <br>
                                {{field}}
                            </div>
                        {%endfor%}
                        <button class ="btn-info" type="submit">Signup</button>
                        <a href="{%url 'login' %}">
                            Back
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}